---
openrpc: 1.2.6
info:
  title: BLE Gateway DM Firmware
  version: 0.0.3
methods:
  - $ref: ./../modules/lib/laird_connect/attributes/attributes/attributes_methods.yml
  - $ref: ./../modules/lib/laird_connect/zephyr_lib/components/attributes/fs_mgmt_methods.yml
components:
  contentDescriptors:
    device_params:
      name: device_parameters
      schema:
        type: array
      x-device-parameters:
        - $ref: ./app/attributes/app_params.yml
        - $ref: ../modules/lib/laird_connect/lwm2m_client/attributes/params.yml
        - $ref: ../modules/lib/laird_connect/lwm2m_firmware_update/attributes/params.yml
        - $ref: ../modules/lib/laird_connect/ble_gateway_device_manager/attributes/params.yml
      x-mg100:
        - $ref: ../modules/lib/laird_connect/ble_gateway_device_manager/attributes/MG100/params.yml
